Repository codesquad-masters2025-team02/issue-tracker, pull requests merged in 2025-06, with the labels that each got.

#178 [Feature] 이슈 메타정보(라벨, 담당자, 마일스톤) 수정 기능 구현 및 사이드바 리팩토링
  frontend/src/features/issue/api/patchIssueContent.ts
  frontend/src/features/issue/api/patchIssueMilestone.ts
  frontend/src/features/issue/api/patchIssueTitle.ts
  frontend/src/features/issue/api/putIssueAssignees.ts
  frontend/src/features/issue/api/putIssueLabels.ts
  frontend/src/features/issue/components/detail/IssueDescription.tsx
  frontend/src/features/issue/components/detail/IssueDetailSidebar.tsx
  frontend/src/features/issue/components/detail/IssueHeader.tsx
  frontend/src/features/issue/components/detail/IssueHeaderActions.tsx
  frontend/src/features/issue/components/detail/IssueMeta.tsx
  frontend/src/features/issue/hooks/usePatchIssueContent.ts
  frontend/src/features/issue/hooks/usePatchIssueMilestone.ts
  frontend/src/features/issue/hooks/usePatchIssueTitle.ts
  frontend/src/features/issue/hooks/usePutIssueAssignees.ts
  frontend/src/features/issue/hooks/usePutIssueLabels.ts
  frontend/src/features/issue/types/issue.ts
  frontend/src/features/newIssue/components/IssueCreateSidebar.tsx
  frontend/src/features/newIssue/components/NewIssueFormSection.tsx
  frontend/src/features/newIssue/reducers/newIssueFormReducer.ts
  frontend/src/pages/IssueDetailPage.tsx
  frontend/src/pages/NewIssuePage.tsx
  frontend/src/shared/components/Dropdown.tsx
  frontend/src/shared/components/TextInput.tsx
  frontend/src/shared/components/sidebar/AssigneeSection.tsx
  frontend/src/shared/components/sidebar/LabelSection.tsx
  frontend/src/shared/components/sidebar/MilestoneSection.tsx
  frontend/src/shared/components/sidebar/index.tsx
  frontend/src/shared/constants/api.ts
  frontend/src/shared/utils/isEqual.ts
Labels: FE, feature, Refactor

#184 [Hotfix] 이슈 상태 변경 시 마일스톤 새로고침
  frontend/src/features/issue/components/detail/IssueHeader.tsx
  frontend/src/features/milestone/hooks/useMilestones.ts
Labels: FE, hotfix

#189 리뷰 반영 및 버그 수정
  backend/src/main/java/elbin_bank/issue_tracker/IssueTrackerApplication.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/presentation/query/CommentQueryController.java
  backend/src/main/java/elbin_bank/issue_tracker/common/advice/GlobalExceptionHandler.java
  backend/src/main/java/elbin_bank/issue_tracker/common/aop/LoggingAspect.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/command/IssueCommandService.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/command/event/IssueMilestoneChangedEvent.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/command/event/IssueMilestoneCreateEvent.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/command/event/IssueMilestoneDeleteEvent.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/command/event/IssueMilestoneStateEvent.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/IssueQueryService.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/dsl/DslParser.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/mapper/IssueDtoMapper.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/domain/Issue.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/strategy/AssigneeFilterStrategy.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/strategy/AuthorFilterStrategy.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/presentation/command/dto/request/IssueMilestoneUpdateRequestDto.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/presentation/query/IssueQueryController.java
  backend/src/main/java/elbin_bank/issue_tracker/label/application/command/LabelCommandService.java
  backend/src/main/java/elbin_bank/issue_tracker/label/domain/LabelCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/label/exception/LabelNameDuplicateException.java
  backend/src/main/java/elbin_bank/issue_tracker/label/infrastructure/command/JdbcLabelCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/milestone/application/command/MilestoneCommandService.java
  backend/src/main/java/elbin_bank/issue_tracker/milestone/application/event/IssueMilestoneChangedListener.java
  backend/src/main/java/elbin_bank/issue_tracker/milestone/application/query/dto/MilestoneDto.java
  backend/src/main/java/elbin_bank/issue_tracker/milestone/application/query/mapper/MilestoneDtoMapper.java
  backend/src/main/java/elbin_bank/issue_tracker/milestone/domain/MilestoneCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/milestone/infrastructure/command/JdbcMilestoneCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/milestone/infrastructure/query/JdbcMilestoneQueryRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/milestone/infrastructure/query/projection/MilestoneProjection.java
  backend/src/main/java/elbin_bank/issue_tracker/milestone/presentation/command/MilestoneCommandController.java
  backend/src/main/java/elbin_bank/issue_tracker/milestone/presentation/command/dto/request/MilestoneUpdateStateRequestDto.java
  backend/src/main/resources/data.sql
  backend/src/test/java/elbin_bank/issue_tracker/IssueTrackerApplicationTests.java
Labels: BE, feature, Refactor, architecture
