Repository codesquad-masters2025-team02/issue-tracker, pull requests merged in 2025-05, with the labels that each got.

#13 [Feature] Spring Boot 프로젝트 세팅
  backend/.gitattributes
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/elbin_bank/issue_tracker/IssueTrackerApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/elbin_bank/issue_tracker/IssueTrackerApplicationTests.java
Labels: BE, feature

#22 [Feature] Issue – 도메인 모델 정의 및 목록 조회/필터링 API 구현
  backend/build.gradle
  backend/src/main/java/elbin_bank/issue_tracker/common/aop/AuditingAspect.java
  backend/src/main/java/elbin_bank/issue_tracker/common/config/AopConfig.java
  backend/src/main/java/elbin_bank/issue_tracker/common/config/WebConfig.java
  backend/src/main/java/elbin_bank/issue_tracker/common/domain/BaseEntity.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/FilterConditionParser.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/FilterCriteria.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/GetFilteredIssueListService.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/dto/IssueSummaryDto.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/dto/IssuesResponseDto.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/domain/Issue.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/domain/IssueRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/domain/IssueStatus.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/IssueQueryBuilder.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/JdbcIssueRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/presentation/IssueQueryController.java
  backend/src/main/java/elbin_bank/issue_tracker/label/application/query/dto/LabelsDto.java
  backend/src/main/java/elbin_bank/issue_tracker/label/domain/Label.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: BE, feature

#26 [Bug] fe 폴더 내부에 배포용 환경 변수 파일 추가
  fe/.env.production
Labels: FE, bug

#31 [Feature] 다크모드 기능 구현
  fe/src/shared/components/DarkModeToggle.tsx
  fe/src/shared/components/Header.tsx
Labels: FE, feature

#37 [Feature] User 도메인 정의 및 ID리스트로 닉네임 조회 기능 추가
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/GetFilteredIssueListService.java
  backend/src/main/java/elbin_bank/issue_tracker/user/domain/User.java
  backend/src/main/java/elbin_bank/issue_tracker/user/domain/UserRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/user/infrastructure/JdbcUserRepository.java
  backend/src/test/java/elbin_bank/issue_tracker/IssueTrackerApplicationTests.java
Labels: BE, feature

#44 [Fix] 대문자 테이블명으로 인한 SQL 조회 오류 수정
  backend/src/main/java/elbin_bank/issue_tracker/common/config/WebConfig.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/IssueQueryBuilder.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/JdbcIssueRepository.java
Labels: BE, bug

#45 [Feature] 테마 컬러 시스템 구조 개선
  fe/src/features/issue/components/list/IssueAdvancedFilter.tsx
  fe/src/features/issue/components/list/IssueListContainer.tsx
  fe/src/features/issue/components/list/IssueListContent.tsx
  fe/src/features/issue/components/list/IssueListHeader.tsx
  fe/src/features/issue/components/list/IssueTabFilter.tsx
  fe/src/features/issue/components/list/issueItem/Assignees.tsx
  fe/src/features/issue/components/list/issueItem/MetaInfo.tsx
  fe/src/features/issue/components/list/issueItem/TitleWithLabels.tsx
  fe/src/features/issue/components/list/issueItem/index.tsx
  fe/src/shared/components/Header.tsx
  fe/src/shared/components/TabButton.tsx
  fe/src/shared/components/TabItem.tsx
  fe/src/shared/styles/globalStyles.ts
  fe/src/shared/styles/theme.common.ts
  fe/src/shared/styles/theme.ts
Labels: FE, Refactor

#70 [Fix] 필터 드롭다운 간격 버그 수정
  fe/src/features/issue/components/list/IssueListHeader.tsx
Labels: FE, component

#73 [Fix] 새 이슈 작성 버튼 클릭 시 이슈 상세로 이동하는 문제 수정
  fe/src/app/router.tsx
Labels: FE, feature

#76 [Chore] Vitest 테스트 환경 및 ESLint 설정 구성
  fe/eslint.config.js
  fe/package-lock.json
  fe/package.json
  fe/src/setupTests.ts
  fe/tsconfig.app.json
  fe/vite.config.ts
Labels: FE

#78 [chore] vitest-fetch-mock 추가 및 테스트 타입 선언 설정
  fe/package-lock.json
  fe/package.json
  fe/tsconfig.app.json
Labels: FE

#84 [Fix] 댓글 리스트에 평탄화된 응답 구조 적용
  fe/src/features/issue/components/detail/CommentList.tsx
Labels: FE, bug

#85 [Feature] 이슈 상세 헤더 UI 및 데이터 연동 구현
  fe/src/features/issue/components/detail/IssueHeader.tsx
  fe/src/pages/IssueDetailPage.tsx
Labels: FE, component

#87 [Refactor] 이슈 상세 페이지 댓글 수 헤더 연동 및 로딩/에러 상태 상위 처리
  fe/src/features/issue/components/detail/CommentList.tsx
  fe/src/features/issue/components/detail/IssueMainSection.tsx
  fe/src/pages/IssueDetailPage.tsx
Labels: FE, Refactor

#89 [Feature] 이슈 상세 댓글 조회 기능 구현
  backend/src/main/java/elbin_bank/issue_tracker/comment/application/query/CommentsQueryRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/application/query/GetCommentsListService.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/application/query/dto/CommentsResponseDto.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/application/query/dto/CommentsSummaryDto.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/application/query/dto/UserDto.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/domain/Comment.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/infrastructure/query/JdbcCommentsQueryRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/presentation/CommentQueryController.java
  backend/src/main/java/elbin_bank/issue_tracker/common/domain/BaseEntity.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/resources/data.sql
  backend/src/test/resources/schema.sql
Labels: BE, feature

#91 [Fix]: dto 필드명 변경
  backend/src/main/java/elbin_bank/issue_tracker/comment/application/query/dto/CommentsSummaryDto.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/application/query/dto/UserDto.java
Labels: BE

#99 [Refactor] content prop 타입을 string | null로 변경
  fe/src/features/issue/components/detail/DescriptionBox.tsx
  fe/src/features/issue/components/detail/IssueMainSection.tsx
Labels: FE, Refactor

#121 [Feature] POST /api/v1/issues – 이슈 생성
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/command/IssueCommandService.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/command/dto/IssueCreateResponseDto.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/domain/Issue.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/domain/IssueCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/command/JdbcIssueCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/JdbcIssueQueryRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/presentation/command/IssueCommandController.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/presentation/command/dto/request/IssueCreateRequestDto.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/presentation/query/IssueQueryController.java
  backend/src/main/java/elbin_bank/issue_tracker/label/domain/LabelCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/label/infrastructure/command/JdbcLabelCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/user/domain/UserCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/user/infrastructure/command/JdbcUserCommandRepository.java
  backend/src/test/java/elbin_bank/issue_tracker/issue/presentation/IssueQueryControllerTest.java
Labels: BE, feature

#125 [Feature] 이슈 생성 사이드바 - 담당자/라벨/마일스톤 데이터 패칭 훅 추가
  fe/public/mocks/labels.json
  fe/public/mocks/milestones.json
  fe/public/mocks/users.json
  fe/src/features/label/api.ts
  fe/src/features/label/api/getLabels.ts
  fe/src/features/label/hooks.ts
  fe/src/features/label/hooks/useLabels.ts
  fe/src/features/label/types.ts
  fe/src/features/milestone/api.ts
  fe/src/features/milestone/api/getMilestonesShort.ts
  fe/src/features/milestone/hooks.ts
  fe/src/features/milestone/hooks/useMilestoneShort.ts
  fe/src/features/milestone/types.ts
  fe/src/features/user/api.ts
  fe/src/features/user/api/getUsers.ts
  fe/src/features/user/hooks.ts
  fe/src/features/user/hooks/useUsers.ts
  fe/src/features/user/types.ts
  fe/src/shared/constants/api.ts
Labels: FE, feature

#148 [Feature] 댓글 수정 API 구현
  backend/src/main/java/elbin_bank/issue_tracker/comment/application/command/CommentCommandService.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/domain/CommentCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/exception/CommentNotFoundException.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/infrastructure/command/JdbcCommentCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/infrastructure/query/JdbcCommentsQueryRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/presentation/command/CommentCommandController.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/presentation/command/dto/request/CommentUpdateRequestDto.java
  backend/src/main/java/elbin_bank/issue_tracker/common/advice/GlobalExceptionHandler.java
Labels: BE, feature

#154 [Feature] 집계 업데이트 로직 구현 및 버그 수정
  backend/src/main/java/elbin_bank/issue_tracker/common/config/FilterConfig.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/command/IssueCommandService.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/event/IssueClosedEvent.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/event/IssueCreatedEvent.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/event/IssueReopenedEvent.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/IssueQueryService.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/mapper/IssueDtoMapper.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/domain/Issue.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/domain/IssueCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/command/JdbcIssueCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/JdbcIssueQueryRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/SqlBuilder.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/SqlClauseResult.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/projection/IssueProjection.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/strategy/AssigneeFilterStrategy.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/strategy/AuthorFilterStrategy.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/strategy/FilterStrategy.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/strategy/LabelFilterStrategy.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/strategy/MilestoneFilterStrategy.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/query/strategy/StateFilterStrategy.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/infrastructure/readmodel/IssueStatusCountUpdater.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/presentation/command/IssueCommandController.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/presentation/command/dto/request/IssueStateUpdateRequestDto.java
  backend/src/main/java/elbin_bank/issue_tracker/s3/application/S3Service.java
  backend/src/main/java/elbin_bank/issue_tracker/s3/presentation/S3Controller.java
  backend/src/main/resources/data.sql
  backend/src/test/java/elbin_bank/issue_tracker/issue/presentation/IssueQueryControllerTest.java
Labels: BE, feature, bug, performance, enhancement

#160 [Feature] 라벨 생성/수정 API 구현
  backend/src/main/java/elbin_bank/issue_tracker/comment/domain/Comment.java
  backend/src/main/java/elbin_bank/issue_tracker/comment/presentation/command/CommentCommandController.java
  backend/src/main/java/elbin_bank/issue_tracker/common/advice/GlobalExceptionHandler.java
  backend/src/main/java/elbin_bank/issue_tracker/issue/application/query/IssueQueryService.java
  backend/src/main/java/elbin_bank/issue_tracker/label/application/command/LabelCommandService.java
  backend/src/main/java/elbin_bank/issue_tracker/label/application/query/repository/LabelQueryRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/label/domain/Label.java
  backend/src/main/java/elbin_bank/issue_tracker/label/domain/LabelCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/label/exception/LabelNotFoundException.java
  backend/src/main/java/elbin_bank/issue_tracker/label/infrastructure/command/JdbcLabelCommandRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/label/infrastructure/query/JdbcLabelQueryRepository.java
  backend/src/main/java/elbin_bank/issue_tracker/label/presentation/command/LabelCommandController.java
  backend/src/main/java/elbin_bank/issue_tracker/label/presentation/command/dto/request/LabelCreateRequestDto.java
  backend/src/main/java/elbin_bank/issue_tracker/label/presentation/command/dto/request/LabelUpdateRequestDto.java
Labels: BE, feature
